"""Zespół hotelu — spójny ze sekcją „Nasz zespół” na stronie głównej."""

TEAM_CATALOG = [
    {
        "Employee_Id": "EMP001",
        "First_Name": "Anna",
        "Last_Name": "Kowalska",
        "Departments": "Dyrektor hotelu",
        "Email": "anna.kowalska@hotelaladu.pl",
        "Mobile_Number": 48123456001,
        "Joining_Date": "2018-04-01",
        "Dateof_Birth": "1982-06-15",
        "Gender": "K",
        "Blood_Group": "A+",
        "Education": "Turystyka i rekreacja",
        "Personal_Identity": "82061512345",
        "Guardian": "—",
        "Guardian_Number": 0,
        "Address": "ul. Floriańska 14, Kraków",
        "photo": "team1.jpg",
    },
    {
        "Employee_Id": "EMP002",
        "First_Name": "Marek",
        "Last_Name": "Nowak",
        "Departments": "Kierownik recepcji",
        "Email": "marek.nowak@hotelaladu.pl",
        "Mobile_Number": 48123456002,
        "Joining_Date": "2019-09-01",
        "Dateof_Birth": "1990-11-22",
        "Gender": "M",
        "Blood_Group": "0+",
        "Education": "Hotelarstwo",
        "Personal_Identity": "90112298765",
        "Guardian": "—",
        "Guardian_Number": 0,
        "Address": "ul. Floriańska 14, Kraków",
        "photo": "team2.jpg",
    },
    {
        "Employee_Id": "EMP003",
        "First_Name": "Katarzyna",
        "Last_Name": "Wiśniewska",
        "Departments": "Szefowa kuchni",
        "Email": "katarzyna.wisniewska@hotelaladu.pl",
        "Mobile_Number": 48123456003,
        "Joining_Date": "2017-02-15",
        "Dateof_Birth": "1988-03-08",
        "Gender": "K",
        "Blood_Group": "B+",
        "Education": "Gastronomia",
        "Personal_Identity": "88030845678",
        "Guardian": "—",
        "Guardian_Number": 0,
        "Address": "ul. Floriańska 14, Kraków",
        "photo": "team3.jpg",
    },
    {
        "Employee_Id": "EMP004",
        "First_Name": "Ewa",
        "Last_Name": "Zielińska",
        "Departments": "Kierowniczka housekeeping",
        "Email": "ewa.zielinska@hotelaladu.pl",
        "Mobile_Number": 48123456004,
        "Joining_Date": "2020-05-10",
        "Dateof_Birth": "1992-07-30",
        "Gender": "K",
        "Blood_Group": "AB+",
        "Education": "Zarządzanie hotelami",
        "Personal_Identity": "92073011223",
        "Guardian": "—",
        "Guardian_Number": 0,
        "Address": "ul. Floriańska 14, Kraków",
        "photo": "team4.jpg",
    },
    {
        "Employee_Id": "EMP005",
        "First_Name": "Tomasz",
        "Last_Name": "Lewandowski",
        "Departments": "Konsjerż",
        "Email": "tomasz.lewandowski@hotelaladu.pl",
        "Mobile_Number": 48123456005,
        "Joining_Date": "2021-01-20",
        "Dateof_Birth": "1995-12-01",
        "Gender": "M",
        "Blood_Group": "A-",
        "Education": "Filologia romańska",
        "Personal_Identity": "95120133445",
        "Guardian": "—",
        "Guardian_Number": 0,
        "Address": "ul. Floriańska 14, Kraków",
        "photo": "team5.jpg",
    },
]

TEAM_PHOTOS = {item["Employee_Id"]: item["photo"] for item in TEAM_CATALOG}


def static_team_photo(employee):
    if employee.Upload_Image:
        return None
    return TEAM_PHOTOS.get(employee.Employee_Id, "team1.jpg")
