# Generated by Django 4.2.8 on 2026-05-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_add_salarys'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_booking',
            name='Room_Type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='City',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Country',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/'),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Nid_No',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
