# Generated by Django 4.2.8 on 2026-06-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0009_alter_online_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_room',
            name='Room_Image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
