# Generated by Django 4.2.8 on 2026-06-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0010_room_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_room',
            name='Room_Capacity',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maks. liczba pokoi tego typu dostępnych w jednej nocy'),
        ),
    ]
