# Generated by Django 4.2.8 on 2026-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0011_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_employee',
            name='Upload_Image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
